package:
  name: ros
  version: 2020.03.23

source:
  - git_url: https://github.com/ros2-gbp/ament_package-release.git
    git_rev: release/eloquent/ament_package/0.8.8-1
    folder: ros-eloquent-ament-package/src/work

build:
  number: 0
  skip: true  # [not win64]

outputs:
  - name: ros-eloquent-ament-package
    version: 0.8.8
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - cmake
      host:
        - flake8
        - pytest
        - python {{ python }}
        - setuptools
      run:
        - python {{ python }}
        - setuptools
    script: bld_ament_python.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - seanyen
